//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Libros
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Resumen { get; set; }
        public string Autor { get; set; }
        public string Editorial { get; set; }
        public Nullable<System.DateTime> Lanzamiento { get; set; }
        public int Idioma { get; set; }
        public Nullable<int> Paginas { get; set; }
        public int Categoria { get; set; }
        public virtual Categorias Categorias { get; set; }
        public virtual Idiomas Idiomas { get; set; }
    }
}
